"""Install an OpenCode plugin that records sessions and reminds on compact."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from skstate.hooks.common import (
    MANAGED_FLAG,
    assert_project_dir,
    hook_command_parts,
)

PLUGIN_NAME = "skstate.js"
MANAGED_HEADER = f"// {MANAGED_FLAG}: true"
PLUGIN_DIRS = ("plugin", "plugins")

COMPACT_NOTE = (
    "压缩之后调用 skstate_context。"
    "下一步只使用返回的 procedure、state、observation。"
)


def build_plugin_source() -> str:
    commands = {
        "session_start": hook_command_parts("session_start"),
        "session_end": hook_command_parts("session_end"),
    }
    commands_json = json.dumps(commands)
    note_json = json.dumps(COMPACT_NOTE, ensure_ascii=False)
    return f"""{MANAGED_HEADER}
// Generated by `skstate hooks --platform opencode`.
// Session hooks record start/end. Compaction keeps the host on the instrument.

const {{ spawnSync }} = require('node:child_process');
const CMDS = {commands_json};
const COMPACT_NOTE = {note_json};

function runHook(name, payload) {{
  try {{
    const parts = CMDS[name];
    if (!parts || !parts.length) return;
    spawnSync(parts[0], parts.slice(1), {{
      input: JSON.stringify(payload || {{}}),
      encoding: 'utf8',
      timeout: 8000,
    }});
  }} catch {{
    // Hook failures must not break the IDE session.
  }}
}}

const Skstate = async () => ({{
  event: async ({{ event }}) => {{
    if (!event || typeof event.type !== 'string') return;
    if (event.type === 'session.created') {{
      const info = event.properties && event.properties.info;
      runHook('session_start', {{ session_id: info && info.id }});
      return;
    }}
    if (event.type === 'session.idle') {{
      runHook('session_end', {{
        session_id: event.properties && event.properties.sessionID,
      }});
    }}
  }},
  'experimental.session.compacting': async (_input, output) => {{
    if (output && Array.isArray(output.context)) {{
      output.context.push(COMPACT_NOTE);
    }}
  }},
}});

module.exports = {{ Skstate }};
module.exports.default = Skstate;
"""


def _plugin_paths(root: Path) -> list[Path]:
    return [root / ".opencode" / dirname / PLUGIN_NAME for dirname in PLUGIN_DIRS]


def _write(path: Path, source: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(source, encoding="utf-8")


def _is_managed(path: Path) -> bool:
    if not path.exists():
        return False
    try:
        return f"{MANAGED_FLAG}: true" in path.read_text(encoding="utf-8")
    except OSError:
        return False


def install(project_dir: str | Path, force: bool = False) -> dict[str, Any]:
    root = assert_project_dir(project_dir)
    source = build_plugin_source()
    written: list[str] = []
    skipped = False
    for path in _plugin_paths(root):
        if path.exists() and not force and _is_managed(path):
            skipped = True
            written.append(str(path))
            continue
        _write(path, source)
        written.append(str(path))
    return {
        "platform": "opencode",
        "project_dir": str(root),
        "plugins": written,
        "skipped_existing": skipped,
    }


def uninstall(project_dir: str | Path) -> dict[str, Any]:
    root = assert_project_dir(project_dir)
    removed: list[str] = []
    for path in _plugin_paths(root):
        if _is_managed(path):
            path.unlink()
            removed.append(str(path))
    return {"platform": "opencode", "removed": removed}


def status(project_dir: str | Path) -> dict[str, Any]:
    root = Path(project_dir).expanduser().resolve()
    present = [str(path) for path in _plugin_paths(root) if _is_managed(path)]
    return {"platform": "opencode", "installed": bool(present), "plugins": present}
